import { Route, Routes } from "react-router-dom";
import {
  AllOrders,
  AllProducts,
  Attributes,
  BannerPage,
  BlogComment,
  Blogs,
  Canceled,
  Categories,
  CommonPages,
  CouponPage,
  CreateAttributes,
  CreateBanner,
  CreateBlog,
  CreateCategory,
  CreateCoupon,
  CreateEmi,
  CreateFaq,
  CreateMenu,
  CreateNotification,
  CreatePage,
  CreateProduct,
  CreateProfile,
  CreateService,
  CreateShipping,
  CreateSlider,
  CreateVideo,
  CustomOrder,
  Customers,
  Delivered,
  EmiPage,
  Error,
  FaqPage,
  Home,
  Menus,
  Notification,
  OrderView,
  PaymentMessage,
  PendingOrders,
  Profile,
  Queries,
  Replay,
  Reviews,
  Services,
  Settings,
  SetupPage,
  Shipping,
  Sliders,
  Staff,
  StockOutProducts,
  Subscriber,
  TicketPage,
  UpdateAttribute,
  UpdateBanner,
  UpdateBlog,
  UpdateCategory,
  UpdateCoupon,
  UpdateEmi,
  UpdateFaq,
  UpdateMenu,
  UpdateOrder,
  UpdatePage,
  UpdateProduct,
  UpdateService,
  UpdateShipping,
  UpdateSlider,
  UpdateVideo,
  VideosPage,
  Warranty,
  WarrantyDetails,
  Csv,
  CreateRole,
  Roles,
  UpdateRole,
  UpdateProfile,
  SettingPage,
} from "./pages";
import CustomInvoice from "./orders/custom-invoice";

const routes = [
  { path: "/", element: <Home /> },
  { path: "/category", element: <Categories /> },
  { path: "/categories/create", element: <CreateCategory /> },
  { path: "/categories/edit/:slug", element: <UpdateCategory /> },
  { path: "/products", element: <AllProducts /> },
  { path: "/products/edit/:slug", element: <UpdateProduct /> },
  { path: "/products/create", element: <CreateProduct /> },
  { path: "/products/stockout", element: <StockOutProducts /> },
  { path: "/products/reviews", element: <Reviews /> },
  { path: "/attributes", element: <Attributes /> },
  { path: "/attributes/create", element: <CreateAttributes /> },
  { path: "/attributes/edit/:slug", element: <UpdateAttribute /> },
  { path: "/orders", element: <AllOrders /> },
  { path: "/csv", element: <Csv /> },
  { path: "/orders/pending", element: <PendingOrders /> },
  { path: "/orders/delivered", element: <Delivered /> },
  { path: "/orders/canceled", element: <Canceled /> },
  { path: "/orders/custom", element: <CustomOrder /> },
  { path: "/orders/custom-invoice", element: <CustomInvoice /> },
  { path: "/orders/views/:slug", element: <OrderView /> },
  { path: "/orders/edit/:slug", element: <UpdateOrder /> },
  { path: "/refund", element: <Warranty /> },
  { path: "/refund/:slug", element: <WarrantyDetails /> },
  { path: "/blogs", element: <Blogs /> },
  { path: "/blogs/create", element: <CreateBlog /> },
  { path: "/blogs/edit/:slug", element: <UpdateBlog /> },
  { path: "/blogs/comments", element: <BlogComment /> },
  { path: "/customers", element: <Customers /> },
  { path: "/videos", element: <VideosPage /> },
  { path: "/videos/create", element: <CreateVideo /> },
  { path: "/videos/edit/:slug", element: <UpdateVideo /> },
  { path: "/faqs", element: <FaqPage /> },
  { path: "/faqs/create", element: <CreateFaq /> },
  { path: "/faqs/edit/:slug", element: <UpdateFaq /> },
  { path: "/coupons", element: <CouponPage /> },
  { path: "/coupons/create", element: <CreateCoupon /> },
  { path: "/coupons/edit/:slug", element: <UpdateCoupon /> },
  { path: "/banner", element: <BannerPage /> },
  { path: "/banner/edit/:slug", element: <UpdateBanner /> },
  { path: "/banner/create", element: <CreateBanner /> },
  { path: "/shipping", element: <Shipping /> },
  { path: "/shipping/create", element: <CreateShipping /> },
  { path: "/shipping/edit/:slug", element: <UpdateShipping /> },
  { path: "/support", element: <TicketPage /> },
  { path: "/support/:slug", element: <Replay /> },
  { path: "/queries", element: <Queries /> },
  { path: "/subscriber", element: <Subscriber /> },
  { path: "/emi", element: <EmiPage /> },
  { path: "/emi/create", element: <CreateEmi /> },
  { path: "/emi/edit/:slug", element: <UpdateEmi /> },
  { path: "/payment-message", element: <PaymentMessage /> },
  { path: "/setup/home-page", element: <SetupPage /> },
  { path: "/setup/setting", element: <Settings /> },
  { path: "/setup/menus/create", element: <CreateMenu /> },
  { path: "/setup/menus/edit/:slug", element: <UpdateMenu /> },
  { path: "/setup/menus", element: <Menus /> },
  { path: "/setup/sliders", element: <Sliders /> },
  { path: "/setup/services", element: <Services /> },
  { path: "/setup/services/create", element: <CreateService /> },
  { path: "/setup/services/edit/:slug", element: <UpdateService /> },
  { path: "/setup/sliders/edit/:slug", element: <UpdateSlider /> },
  { path: "/setup/sliders/create", element: <CreateSlider /> },
  { path: "/setup/pages", element: <CommonPages /> },
  { path: "/setup/pages/create", element: <CreatePage /> },
  { path: "/setup/pages/edit/:slug", element: <UpdatePage /> },
  { path: "/notification", element: <Notification /> },
  { path: "/notification/create", element: <CreateNotification /> },
  { path: "/admin/profile/:slug", element: <Profile /> },
  { path: "/staffs", element: <Staff /> },
  { path: "/staffs/create", element: <CreateProfile /> },
  { path: "/staffs/edit/:slug", element: <UpdateProfile /> },
  { path: "/roles", element: <Roles /> },
  { path: "/roles/create", element: <CreateRole /> },
  { path: "/roles/edit/:slug", element: <UpdateRole /> },
  { path: "/manage-settings", element: <SettingPage /> },
  { path: "*", element: <Error /> }, // 404 Page
];

function PageRoutes() {
  return (
    <Routes>
      <>
        {routes.map((route, index) => (
          <Route key={index} path={route.path} element={route.element} />
        ))}
      </>
    </Routes>
  );
}
export default PageRoutes;
